str = ''
str += '<div id="footer">'
str += '	<div class="f_wrap">'
str += '		<div class="f_logo"><img src="img/common/f_logo.png" alt="관현맹인전통예술단"></div>'
str += '		<div class="info">'
str += '			<ul class="terms">'
str += '				<li><a href="privacy.html">개인정보처리방침</a><span class="bar"></span></li>'
str += '				<li><a href="email.html">이메일무단수집거부</a></li>'
str += '			</ul>'
str += '			<p>(08757) 서울특별시 관악구 남부순환로 1717</p>'
str += '			<ul class="add">'
str += '				<li>Tel. 02-880-0690 ~ 0695<span class="bar"></span></li>'
str += '				<li>Fax. 02-887-1120<span class="bar"></span></li>'
str += '				<li>E-mail. ktmob@naver.com</li>'
str += '			</ul>'
str += '		</div>'
str += '		<div class="f_sns">'
str += '			<ul>'
str += '				<li class="facebook"><a href="#" target="_blank" title="새창열림">페이스북</a></li>'
str += '				<li class="blog"><a href="#" target="_blank" title="새창열림">블로그</a></li>'
str += '				<li class="youtube"><a href="#" target="_blank" title="새창열림">유튜브</a></li>'
str += '				<li class="instagram"><a href="#" target="_blank" title="새창열림">인스타그램</a></li>'
str += '			</ul>'
str += '		</div>'
str += '	</div>'
str += '</div>'

document.write( str );