str = ''
str += '<div id="header">'
str += ''
str += '	<div class="top_area">'
str += '		<ul class="lst_link">'
str += '			<li><a href="index.html">HOME</a><span class="bar"></span></li>'
str += '			<li><a href="sitemap.html">사이트맵</a></li>'
str += '		</ul>'
str += ''		
str += '		<h1 class="logo">'
str += '			<a href="index.html"><img src="img/common/logo.png" alt="관현맹인전통예술단" /></a>'
str += '		</h1>'
str += ''
str += '		<ul class="lst_sns">'
str += '			<li class="facebook"><a href="#" target="_blank" title="새창열림">페이스북</a></li>'
str += '			<li class="blog"><a href="#" target="_blank" title="새창열림">블로그</a></li>'
str += '			<li class="youtube"><a href="#" target="_blank" title="새창열림">유튜브</a></li>'
str += '			<li class="instagram"><a href="#" target="_blank" title="새창열림">인스타그램</a></li>'
str += '		</ul>'
str += '	</div>'
str += ''
str += '	<div class="h_group_wrap">'
str += '		<div class="h_group">'
str += ''
str += '			<div>'
str += '				<div id="gnb">'
str += '					<button type="button" class="btn_menu">전체메뉴 열기</button>'
str += '					<div class="box">'
str += '						<button type="button" class="btn_close">전체메뉴 닫기</button>'
str += ''
str += '						<!-- link -->'
str += ''
str += '						<div class="link_area">'
str += '							<ul>'
str += '								<li><a href="index.html">HOME</a><span class="bar"></span></li>'
str += '								<li><a href="sitemap.html">사이트맵</a></li>'
str += '							</ul>'
str += '						</div>'
str += ''
str += '						<!-- sns -->'
str += ''
str += '						<div class="sns_area">'
str += '							<ul>'
str += '								<li class="facebook"><a href="#" target="_blank">페이스북</a></li>'
str += '								<li class="blog"><a href="#" target="_blank">블로그</a></li>'
str += '								<li class="youtube"><a href="#" target="_blank">유튜브</a></li>'
str += '								<li class="instagram"><a href="#" target="_blank">인스타그램</a></li>'
str += '							</ul>'
str += '						</div>'
str += ''
str += '						<ul>'
str += '							<li><a href="javascript:">예술단소개</a>'
str += '								<div class="sub_menu">'
str += '									<ul>'
str += '										<li><a href="intro.html">관현맹인전통예술단</a></li>'
str += '										<li><a href="history.html">예술단 주요 연혁</a></li>'
str += '										<li><a href="member.html">예술단원소개</a></li>'
str += '										<li><a href="contact.html">찾아오시는 길</a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</li>'
str += '							<li><a href="javascript:">공연안내</a>'
str += '								<div class="sub_menu">'
str += '									<ul>'
str += '										<li><a href="schedule.html">행사일정</a></li>'
str += '										<li><a href="photo_list.html">공연사진</a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</li>'
str += '							<li><a href="javascript:">작품소개</a>'
str += '								<div class="sub_menu">'
str += '									<ul>'
str += '										<li><a href="album.html">음반</a></li>'
str += '										<li><a href="library.html">관련도서</a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</li>'
str += '							<li><a href="javascript:">단원양성</a>'
str += '								<div class="sub_menu">'
str += '									<ul>'
str += '										<li><a href="music.html">전통음악교육</a></li>'
str += '										<li><a href="camp.html">성공사례</a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</li>'
str += '							<li><a href="javascript:">나눔마당</a>'
str += '								<div class="sub_menu">'
str += '									<ul>'
str += '										<li><a href="guide.html">후원안내</a></li>'
str += '										<li><a href="sponsor.html">후원신청</a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</li>'
str += '							<li><a href="javascript:">알림마당</a>'
str += '								<div class="sub_menu">'
str += '									<ul>'
str += '										<li><a href="notice_list.html">공지사항</a></li>'
str += '										<li><a href="news_list.html">보도자료</a></li>'
str += '										<li><a href="review_list.html">공연후기</a></li>'
str += '									</ul>'
str += '								</div>'
str += '							</li>'
str += '						</ul>'
str += '					</div>'
str += ''
str += '				</div>'
str += ''
str += '			</div>'
str += '		</div>'
str += ''
str += '	</div>'
str += '</div>'

document.write(str);